### ISSUE TITLE
The actual GPUs used are inconsistent with the allocated ones

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#1227]
**Describe the bug**

**Steps to reproduce**

1. Install GPUStack using the following config file.
```
resources:
 gpu_devices:
  - name: 'NVIDIA 3090'                  # Name of the GPU
    vendor: NVIDIA             # Vendor of the GPU (supported values: NVIDIA, Moore Threads, Apple, Huawei)
    index: 0                    # Index if the GPU
    memory:
      total: 25769803776        # Total memory size of the GPU in byte
  - name: 'NVIDIA 3090'                  # Name of the GPU
    vendor: NVIDIA             # Vendor of the GPU (supported values: NVIDIA, Moore Threads, Apple, Huawei)
    index: 2                   # Index if the GPU
    memory:
      total: 25769803776        # Total memory size of the GPU in byte
  - name: 'NVIDIA 3090'                  # Name of the GPU
    vendor: NVIDIA             # Vendor of the GPU (supported values: NVIDIA, Moore Threads, Apple, Huawei)
    index: 3                   # Index if the GPU
    memory:
      total: 25769803776        # Total memory size of the GPU in byte
  - name: 'NVIDIA 4070'                  # Name of the GPU
    vendor: NVIDIA             # Vendor of the GPU (supported values: NVIDIA, Moore Threads, Apple, Huawei)
    index: 1                   # Index if the GPU
    memory:
      total: 12878610432        # Total memory size of the GPU in byte
```
 
2. Deploy the `Hugging Face/Qwen/Qwen2.5-0.5B-Instruct-GGUF` model with default parameters.
3. Check the GPU used by the model instance.

**Result**

1. GPUs 0 and 2 were allocated, but actually GPUs 0 and 3 were used.
<img width="1026" alt="Image" src="https://github.com/user-attachments/assets/5dee4950-b78e-4fbc-ac24-017f5565e7ad" />

<img width="2679" alt="Image" src="https://github.com/user-attachments/assets/8d1d5c79-756b-4882-9620-e62defe91ebe" />

<img width="956" alt="Image" src="https://github.com/user-attachments/assets/190bc26a-a72d-4eba-9e8c-a79035a02cba" />

**Environment**

- GPUStack version: v0.5.1
- OS: Ubuntu 22.04

**Additional context**
