### ISSUE TITLE
Allocated VARM of custom GPU resources not updated after stopping model instance

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#1354]
**Steps to reproduce**

1. Install GPUStack using custom GPU resources

```
resources:
    gpu_devices:
        - name: 'NVIDIA TEST'
          vendor: NVIDIA
          index: 0
          memory:
            total: 85899345920
        - name: 'NVIDIA TEST'
          vendor: NVIDIA
          index: 1
          memory:
            total: 85899345920
        - name: 'NVIDIA TEST'
          vendor: NVIDIA
          index: 2
          memory:
            total: 85899345920
        - name: 'NVIDIA TEST'
          vendor: NVIDIA
          index: 3
          memory:
            total: 85899345920
        - name: 'NVIDIA TEST'
          vendor: NVIDIA
          index: 4
          memory:
            total: 85899345920
        - name: 'NVIDIA TEST'
          vendor: NVIDIA
          index: 5
          memory:
            total: 85899345920
        - name: 'NVIDIA TEST'
          vendor: NVIDIA
          index: 6
          memory:
            total: 85899345920
        - name: 'NVIDIA TEST'
          vendor: NVIDIA
          index: 7
          memory:
            total: 85899345920
```

2. Deploy some models.
3. Go to `Resources` and check the VRAM usage.
4. Stop all model instances.
5. Repeat step 3.

**Result**

1. After stop all instances, the allocated VARM displayed on the UI is not updated

<img width="2748" alt="Image" src="https://github.com/user-attachments/assets/035f3528-b92b-4787-b241-fcc93ce06d96" />

<img width="926" alt="Image" src="https://github.com/user-attachments/assets/7400def0-da44-453d-86c9-a1ecf7d71e40" />

2. However, when deploying a new model and checking the logs of the GPUStack server the, allocatable VRAM is correct.
```
2025-02-27T14:32:04+08:00 - gpustack.policies.utils - DEBUG - Worker worker_1 reserved memory: 2147483648, reserved gpu memory: 1073741824, allocatable memory: 64964702208, allocatable gpu memory: {0: 84825604096, 1: 84825604096, 2: 84825604096, 3: 84825604096, 4: 84825604096, 5: 84825604096, 6: 84825604096, 7: 84825604096}
```

**Environment**

- GPUStack version: main 8b60bdb
- OS: Ubuntu 22.04
- GPU: 8x80G

**Additional context**
