### ISSUE TITLE
Support for user-defined worker resources

### ISSUE THREAD

**Issue by aiwantaozi** [gpustack/gpustack#310]
**Is your enhancement related to a problem? Please describe.**

We hope that even if we currently do not support detecting certain GPU vendors, GPUStack can still be used.

**Describe the solution you'd like**

Support for user-defined worker GPU resources. Currently, we automatically detect the worker's resources. When some GPUs cannot be automatically detected, we allow users to define the worker resources manually. Based on the user-defined resources, we can infer the appropriate inference engine.

**Comment by aiwantaozi** [comment]
For test.

1. by configuring the `--config-file` flag to define the GPU resources.
```yaml
server_url: http://myserver
token: mytoken

# Customize the GPU resources
resources:
  gpu_devices:
  - name: 910B                  # Name of the GPU
    vendor: Huawei              # Vendor of the GPU (supported values: NVIDIA, Moore Threads, Apple, Huawei)
    index: 0                    # Index if the GPU
    memory:
      total: 22906503168        # Total memory size of the GPU in byte
      is_unified_memory: true   # Indicates if it is unified memory, like Apple M series
```

2. check whether we could set the resource to the worker's status
3. deploy model, double check we could use the collect llama-box based on the vendor.
4. check the resources UI
